export default {
  PREFIX: 'NAGME_GLOBAL',

  SET_ITEM_DATA: 'SET_ITEM_DATA',
  RESET_ITEM_DATA: 'RESET_ITEM_DATA',

  CREATE_ITEM: 'CREATE_ITEM',
  CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
  CREATE_ITEM_FAILED: 'CREATE_ITEM_FAILED',

  UPDATE_ITEM: 'UPDATE_ITEM',
  UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_FAILED: 'UPDATE_ITEM_FAILED'
}
