const DEFAULT_DATE_FORMAT = 'YYYY-MM-DD'
const DATE_DAY_TIME_YEAR_FORMAT = 'HH:mm dddd MMMM Do YYYY'
const DATE_DAY_YEAR_FORMAT = 'dddd MMMM Do YYYY'
const WEEK_DAY_DATE_FORMAT = 'dddd Do MMMM YYYY'
const TIME_DEFAULT_FORMAT = 'HH:mm'
const TIME_TRIMMED_FORMAT = 'HHmm'
const DATEPICKER_DATE_FORMAT = 'Do MMMM YYYY'
const DEFAULT_DATE_TIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss'

export {
  DATE_DAY_TIME_YEAR_FORMAT,
  DATE_DAY_YEAR_FORMAT,
  DEFAULT_DATE_FORMAT,
  WEEK_DAY_DATE_FORMAT,
  TIME_DEFAULT_FORMAT,
  DATEPICKER_DATE_FORMAT,
  TIME_TRIMMED_FORMAT,
  DEFAULT_DATE_TIME_FORMAT
}
