export default {
  PREFIX: 'STATS',

  FETCH_USER_FILTER: 'FETCH_USER_FILTER',
  FETCH_USER_FILTER_SUCCESS: 'FETCH_USER_FILTER_SUCCESS',
  FETCH_USER_FILTER_FAILED: 'FETCH_USER_FILTER_FAILED',
  RESET_USER_FILTER: 'RESET_USER_FILTER',

  FETCH_CONFIG: 'FETCH_CONFIG',
  FETCH_CONFIG_SUCCESS: 'FETCH_CONFIG_SUCCESS',
  FETCH_CONFIG_FAILED: 'FETCH_CONFIG_FAILED',

  ADD_FILTER: 'ADD_FILTER',
  ADD_FILTER_SUCCESS: 'ADD_FILTER_SUCCESS',
  ADD_FILTER_FAILED: 'ADD_FILTER_FAILED',

  UPDATE_FILTER_SET: 'UPDATE_FILTER_SET',
  DELETE_FILTER_SET: 'DELETE_FILTER_SET',

  UPDATE_SORTING: 'UPDATE_SORTING',

  DELETE_FILTER: 'DELETE_FILTER',
  UPDATE: 'UPDATE',

  DELETE_STAT: 'DELETE_STAT',
  DELETE_STAT_SUCCESS: 'DELETE_STAT_SUCCESS',
  DELETE_STAT_FAILED: 'DELETE_STAT_FAILED',

  DOWNLOAD_SELECTIONS: 'DOWNLOAD_SELECTIONS',

  ADD_STAT: 'ADD_STAT',
  ADD_STAT_SUCCESS: 'ADD_STAT_SUCCESS',
  ADD_STAT_FAILED: 'ADD_STAT_FAILED',

  FETCH_STATS: 'FETCH_STATS',
  FETCH_STATS_SUCCESS: 'FETCH_STATS_SUCCESS',
  FETCH_STATS_FAILED: 'FETCH_STATS_FAILED',

  FETCH_CHART_DATA: 'FETCH_CHART_DATA',
  FETCH_CHART_DATA_SUCCESS: 'FETCH_CHART_DATA_SUCCESS',
  FETCH_CHART_DATA_FAILED: 'FETCH_CHART_DATA_FAILED',
  RESET_SHOW_CHART: 'RESET_SHOW_CHART'
}
