export default {
  PREFIX: 'LEADERBOARD',

  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
  FETCH_NAP_DATA: 'FETCH_NAP_DATA',
  FETCH_NAP_DATA_SUCCESS: 'FETCH_NAP_DATA_SUCCESS',
  FETCH_NAP_DATA_FAILED: 'FETCH_NAP_DATA_FAILED'
}
