export default {
  PREFIX: 'NAGME',

  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',

  DELETE_NAGME: 'DELETE_NAGME',
  DELETE_NAGME_SUCCESS: 'DELETE_NAGME_SUCCESS',
  DELETE_NAGME_FAILED: 'DELETE_NAGME_FAILED',

  UPDATE_NAGME: 'UPDATE_NAGME',
  UPDATE_NAGME_SUCCESS: 'UPDATE_NAGME_SUCCESS',
  UPDATE_NAGME_FAILED: 'UPDATE_NAGME_FAILED',

  CREATE_NAGME: 'CREATE_NAGME',
  CREATE_NAGME_SUCCESS: 'CREATE_NAGME_SUCCESS',
  CREATE_NAGME_FAILED: 'CREATE_NAGME_FAILED'
}
