export default {
  PREFIX: 'MEMBER_SETTINGS',

  UPDATE_FREEZE_HORSE_NAME: 'UPDATE_FREEZE_HORSE_NAME',
  UPDATE_SYNCHRONISE_SCROLLBAR: 'UPDATE_SYNCHRONISE_SCROLLBAR',

  POLL_START: 'POLL_START',
  POLL_STOP: 'POLL_STOP',
  SAVE_SESSION: 'SAVE_SESSION',

  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',

  FETCH_PROFILE_DATA: 'FETCH_PROFILE_DATA',
  FETCH_PROFILE_DATA_SUCCESS: 'FETCH_PROFILE_DATA_SUCCESS',
  FETCH_PROFILE_DATA_FAILED: 'FETCH_PROFILE_DATA_FAILED',

  FETCH_RACE_COLUMNS: 'FETCH_RACE_COLUMNS',
  FETCH_RACE_COLUMNS_SUCCESS: 'FETCH_RACE_COLUMNS_SUCCESS',
  FETCH_RACE_COLUMNS_FAILED: 'FETCH_RACE_COLUMNS_FAILED',

  UPDATE_TABLE_SETTINGS: 'UPDATE_TABLE_SETTINGS',
  UPDATE_TABLE_SETTINGS_SUCCESS: 'UPDATE_TABLE_SETTINGS_SUCCESS',
  UPDATE_TABLE_SETTINGS_FAILED: 'UPDATE_TABLE_SETTINGS_FAILED',

  UPDATE_MEMBER_SETTINGS: 'UPDATE_MEMBER_SETTINGS',
  UPDATE_MEMBER_SETTINGS_SUCCESS: 'UPDATE_MEMBER_SETTINGS_SUCCESS',
  UPDATE_MEMBER_SETTINGS_FAILED: 'UPDATE_MEMBER_SETTINGS_FAILED',

  UPDATE_PROFILE_SUBSCRIPTION: 'UPDATE_PROFILE_SUBSCRIPTION',
  UPDATE_PROFILE_SUBSCRIPTION_SUCCESS: 'UPDATE_PROFILE_SUBSCRIPTION_SUCCESS',
  UPDATE_PROFILE_SUBSCRIPTION_FAILED: 'UPDATE_PROFILE_SUBSCRIPTION_FAILED'
}
