import { createActions } from 'redux-actions'

import types from './types'

const typesWithoutPrefix = Object.values(types).filter(
  (i) => i !== types.PREFIX
)

export const {
  fetchData,
  fetchDataSuccess,
  fetchDataFailed,
  fetchDetailedData,
  fetchDetailedDataSuccess,
  fetchDetailedDataFailed,
  fetchAllRacesData,
  fetchAllRacesDataSuccess,
  fetchAllRacesDataFailed,
  fetchAllRacesPaginationData,
  fetchAllRacesPaginationDataSuccess,
  fetchAllRacesPaginationDataFailed,
  getComments,
  getCommentsSuccess,
  createComment,
  likeUnlikeComment,
  downloadFile,
  likeUnlikeCommentSuccess,
  deleteComment,
  deleteCommentSuccess,
  getRepliedComment,
  getRepliedCommentSuccess,
  replyComment,
  reportComment,
  changeDate,
  changeCourse,
  resetCourse,
  changeStatsMode,
  changeStartTime,
  resetStartTime,
  changeStartTimesOptions,
  removeSelections,
  removeSelectionsSuccess,
  removeSelectionsFailed,
  removeSelection,
  addSelection,
  addSelectionSuccess,
  addSelectionFailed,
  fetchSelectionData,
  fetchSelectionDataSuccess,
  fetchSelectionDataFailed,
  submitSelections,
  submitSelectionsSuccess,
  submitSelectionsFailed,
  downloadSelections,
  resetSelections,
  resetSelectionsSuccess,
  resetSelectionsFailed,
  addNap,
  addNapSuccess,
  addNapFailed,
  clearEntries,
  fetchNapsData,
  fetchNapsDataSuccess,
  fetchNapsDataFailed,
  submitNaps,
  submitNapsSuccess,
  submitNapsFailed,
  updateNagmeInRaces
} = createActions({}, ...typesWithoutPrefix, { prefix: types.PREFIX })
