export default {
  PREFIX: 'RACES',

  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',

  FETCH_DETAILED_DATA: 'FETCH_DETAILED_DATA',
  FETCH_DETAILED_DATA_SUCCESS: 'FETCH_DETAILED_DATA_SUCCESS',
  FETCH_DETAILED_DATA_FAILED: 'FETCH_DETAILED_DATA_FAILED',

  FETCH_ALL_RACES_DATA: 'FETCH_ALL_RACES_DATA',
  FETCH_ALL_RACES_DATA_SUCCESS: 'FETCH_ALL_RACES_DATA_SUCCESS',
  FETCH_ALL_RACES_DATA_FAILED: 'FETCH_ALL_RACES_DATA_FAILED',

  FETCH_ALL_RACES_PAGINATION_DATA: 'FETCH_ALL_RACES_PAGINATION_DATA',
  FETCH_ALL_RACES_PAGINATION_DATA_SUCCESS:
    'FETCH_ALL_RACES_PAGINATION_DATA_SUCCESS',
  FETCH_ALL_RACES_PAGINATION_DATA_FAILED:
    'FETCH_ALL_RACES_PAGINATION_DATA_FAILED',

  CHANGE_DATE: 'CHANGE_DATE',

  CHANGE_COURSE: 'CHANGE_COURSE',
  RESET_COURSE: 'RESET_COURSE',

  DOWNLOAD_FILE: 'DOWNLOAD_FILE',

  CHANGE_STATS_MODE: 'CHANGE_STATS_MODE',

  GET_COMMENTS: 'GET_COMMENTS',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',

  CREATE_COMMENT: 'CREATE_COMMENT',

  LIKE_UNLIKE_COMMENT: 'LIKE_UNLIKE_COMMENT',
  LIKE_UNLIKE_COMMENT_SUCCESS: 'LIKE_UNLIKE_COMMENT_SUCCESS',

  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',

  GET_REPLIED_COMMENT: 'GET_REPLIED_COMMENT',
  GET_REPLIED_COMMENT_SUCCESS: 'GET_REPLIED_COMMENT_SUCCESS',

  REPLY_COMMENT: 'REPLY_COMMENT',
  REPORT_COMMENT: 'REPORT_COMMENT',

  CHANGE_START_TIMES_OPTIONS: 'CHANGE_START_TIMES_OPTIONS',

  CHANGE_START_TIME: 'CHANGE_START_TIME',
  RESET_START_TIME: 'RESET_START_TIME',

  REMOVE_SELECTIONS: 'REMOVE_SELECTIONS',
  REMOVE_SELECTIONS_SUCCESS: 'REMOVE_SELECTIONS_SUCCESS',
  REMOVE_SELECTIONS_FAILED: 'REMOVE_SELECTIONS_FAILED',

  REMOVE_SELECTION: 'REMOVE_SELECTION',
  ADD_SELECTION: 'ADD_SELECTION',
  ADD_SELECTION_SUCCESS: 'ADD_SELECTION_SUCCESS',
  ADD_SELECTION_FAILED: 'ADD_SELECTION_FAILED',

  RESET_SELECTIONS: 'RESET_SELECTIONS',
  RESET_SELECTIONS_SUCCESS: 'RESET_SELECTIONS_SUCCESS',
  RESET_SELECTIONS_FAILED: 'RESET_SELECTIONS_FAILED',

  FETCH_SELECTION_DATA: 'FETCH_SELECTION_DATA',
  FETCH_SELECTION_DATA_SUCCESS: 'FETCH_SELECTION_DATA_SUCCESS',
  FETCH_SELECTION_DATA_FAILED: 'FETCH_SELECTION_DATA_FAILED',

  SUBMIT_SELECTIONS: 'SUBMIT_SELECTIONS',
  SUBMIT_SELECTIONS_SUCCESS: 'SUBMIT_SELECTIONS_SUCCESS',
  SUBMIT_SELECTIONS_FAILED: 'SUBMIT_SELECTIONS_FAILED',

  DOWNLOAD_SELECTIONS: 'DOWNLOAD_SELECTIONS',

  ADD_NAP: 'ADD_NAP',
  ADD_NAP_SUCCESS: 'ADD_NAP_SUCCESS',
  ADD_NAP_FAILED: 'DELETE_SELECTION_FAILED',
  CLEAR_ENTRIES: 'CLEAR_ENTRIES',

  FETCH_NAPS_DATA: 'FETCH_NAPS_DATA',
  FETCH_NAPS_DATA_SUCCESS: 'FETCH_NAPS_DATA_SUCCESS',
  FETCH_NAPS_DATA_FAILED: 'FETCH_NAPS_DATA_FAILED',

  SUBMIT_NAPS: 'SUBMIT_NAPS',
  SUBMIT_NAPS_SUCCESS: 'SUBMIT_NAPS_SUCCESS',
  SUBMIT_NAPS_FAILED: 'SUBMIT_NAPS_FAILED',

  UPDATE_NAGME_IN_RACES: 'UPDATE_NAGME_IN_RACES'
}
