export default {
  PREFIX: 'DASHBOARD',

  FETCH_LATEST_NAP_SELECTION_DATA: 'FETCH_LATEST_NAP_SELECTION_DATA',
  FETCH_LATEST_NAP_SELECTION_DATA_SUCCESS:
    'FETCH_LATEST_NAP_SELECTION_DATA_SUCCESS',
  FETCH_LATEST_NAP_SELECTION_DATA_FAILED:
    'FETCH_LATEST_NAP_SELECTION_DATA_FAILED'
}
