export default {
  PREFIX: 'GLOBAL_SETTINGS',

  TOGGLE_HIDE_COMMENTS: 'TOGGLE_HIDE_COMMENTS',
  TOGGLE_SHOW_NATIONALITY: 'TOGGLE_SHOW_NATIONALITY',
  TOGGLE_DISABLE_HINTS: 'TOGGLE_DISABLE_HINTS',
  TOGGLE_DISABLE_NOTIFICATIONS: 'TOGGLE_DISABLE_NOTIFICATIONS',
  TOGGLE_SHOW_NONRUNNERS: 'TOGGLE_SHOW_NONRUNNERS',
  TOGGLE_SHOW_FRACTIONAL_ODDS: 'TOGGLE_SHOW_FRACTIONAL_ODDS'
}
